### ISSUE TITLE
Jdbc connector configuration

### ISSUE THREAD

**Issue by peterygates** [CategoricalData/fql#10]
I spoke with David, and the mechanism for configuring FQL to access a particular jdbc connector is a bit awkward. I am opening this issue to suggest that creating a form based strategy for identifying the path to particular jdbc connector and exposing it so that is is available within the IDE would be helpful. This is how RDA worked, although I must say the RDA jdbc connector form was not great, but it was better than requiring that the user create a batch file.

**Comment by wisnesky** [comment]
I've added a pragma to extend the class path at runtime.  It looks like this:

pragma load_mysql_jar = add_to_classpath {
	"/Users/ryan/Desktop/mysql-connector-java-5.1.40-bin.jar"
}

pragma view = exec_jdbc 
	"com.mysql.jdbc.Driver" 
	"jdbc:mysql://localhost:3306/Test?user=root&password=whasabi&useSSL=false"
{ 
	"SELECT * FROM Dept"
	"SELECT * FROM Employee"
}

Unfortunately, this method will likely stop working in Java 9 (due to release in summer 2017).  It will also fail if a SecurityManager is installed in the JVM.  So I don't want to officially support this pragma (it won't turn blue or be mentioned in the manual).  But hopefully it will make your life easier until I can come up with a better solution.

As for GUI support, we'll have to put that in the commercial product, not the free one, and I think NetBeans/Eclipse/etc already has forms like you are suggesting.

**Comment by peterygates** [comment]
I agree with your plan to defer GUI support to the commercial product.
