### ISSUE TITLE
Formalize a URS

### ISSUE THREAD

**Issue by peterygates** [CategoricalData/fql#13]
For Ryan:
1. Create a new label "User Requirement"
2. Create a new milestone "MVP release"
3. Create priority labels High, Medium and Low. Correct me if I am wrong as I think this is the only way we can prioritize with this issue tracking.
4. Check if Jee wants to get involved and if so add him as a GIT Hub user.
3. Ryan has the final word on which requirements will be included in the initial release.

For Peter, Jee and David:
1. Create issues for features we already have and believe we can deliver by the release date. Each such issue would be tagged with the User Requirement label.
2. Think about defining user acceptance tests for each such feature and add a description of that test in a comment associated with the requirement. This would mean we would have a test we would define and execute prior to the release. This process would be documented in as part of a User Acceptance Test (UAT) David, Jee and I could perform.

For now I propose we stick to a light weight strategy that involves documenting everything associated with a user requirement in the comments on the issue for the requirement. More elaborate documentation might involve creating a description of functional and technical specification that detail how each user requirement is implemented. We can defer this until and if there is a request that a customer wants to do a formal validation of our product. Things such as screenshots or tables of data can be loaded as attachments.

**Comment by dspivak** [comment]
Not sure what you want me to do here. For example, should I add "EDs" somewhere and then give tests?

**Comment by peterygates** [comment]
Yes, and I want more. I want you to think about how we can use math to
reduce our test burden. Can we test at an abstract level and claim this
will guarentee many concrete things will work.

**Comment by dspivak** [comment]
I don't see it.... Ryan would probably know better if something like that
makes sense.

**Comment by peterygates** [comment]
Yes, consider what functionality is important to you as a mathematician.
Describe that functionality in a way that it can be verified. Now describe
a verification process that would convince you that that functionality is
working according to your description.

I also want you to consider how you could define a test. Now I want you to
could create a proof that if that test passes a large class of other tests
would pass. I think if we can do things like that it would be yet another
differentiating characteristic of our product.

We claim mathematics can give us high assurance. I believe one opportunity
is to make use of mathematics to increase the efficiency and strength of
the validation process itself.

There is this idea of a trace matrix in the context of validation. Someone
who audits our product will want to be able to follow a trace from each
requirement to one or more tests that verify that requirement is met. I
have always felt that was an opportunity to apply mathematics. Wouldn't it
be interesting if we could define requirements abstractly, verify those
abstract requirements are met and then argue a large number of
"traditional" requirements would be met.

**Comment by DanielCoorey** [comment]
I came to follow Categorical Data in search of a mathematically verifiable
programming language. Apologies for my interruption but, in my experience,
Java is not such a language. I trust you'll be able to verify the
correctness of AQL's transformations but testing all software to a level
that a mathematician would be satisfied with is an even bigger task than
Categorical Data's primary purpose.

**Comment by wisnesky** [comment]
I agree with David and Daniel; I’m all for test-driven development, but I don’t think it makes sense here; for example, as far as I am aware, a theorem prover can’t be decomposed into a set of components that can be individually tested / verified.  Nor do theorem provers themselves compose.  That being said, we can still try to exercise the front end with test cases like “1) create a mapping from a schema that does not exist.  2) create a mapping that targets an attribute that does not exist. 3) …”.  I would like to have a big AQL file of those test cases but haven’t had the time to create one.  

I think our best bet for testing AQL is to have a ton of examples, to make sure that any java code we write directly follows published algorithms (which is the case for all of the provers), that we keep the java part of AQL (the “trusted kernel”) as small as possible, and to build as much as possible in AQL rather than Java.  This is the strategy employed by e.g., Coq.
  
Peter, is this discussion helpful?  This discussion has been about “the validation process itself” for AQL’s codebase, but I could see a different discussion where we try to figure out design patterns for ETL flows that have certain properties by construction.  Such a discussion would not involve validating the AQL codebase.  As an example, we figured out that in the pushout data warehouse pattern, if you use a pushout schema rather than an arbitrary schema and start with consistent instances, the output will be consistent (which isn’t true if you use a non-pushout schema).

**Comment by wisnesky** [comment]
The requested labels, users, and milestones have been added.

**Comment by wisnesky** [comment]
Per our discussion today, I am adding four new issues:

 - positive testing / verification of AQL itself
 - negative testing / verification of AQL itself
 -  positive testing / verification of AQL programs
 -  negative testing / verification of AQL programs

Coming up with user requirements is still a good idea, so I'm leaving this issue open.

**Comment by peterygates** [comment]
Following up on our Wednesday discussion. I have been thinking about Ryan's
idea about verification of AQL programs. I think we need to add to our
marketing pitches that we have an "ETL Validator". ETL workflows are
difficult and expensive to build and debug. The more I think about it the
more I like this idea.

Right now I have some serious concerns about the scalability of the current
incarnation of the tool. This raises the question as to its "sweet spot". I
have long argued that the value of category theory is clarity of thought.
It provides a framework for organizing concepts. The existing incarnation
of the tool is a remarkable vehicle for such clarification.

It's use in a production environment to support regularly scheduled ETL
workflows is not clear to me. I think I can cobble something together to
build a one time load, but I don't see a way to support incremental loads
that makes any sense. This begs the question: "What are we selling". I
think the model management concept is much closer to the mark than an ETL
tool. In that capacity I think the tool shines.

At the risk of over committing I am going to take a serious run at Jee and
Ryan's finance colimit model. I want to experiment with that model to see
if I can use the tool to understand the concepts therein. I don't know much
about this domain, but I predict if I use the tool as a way to examine and
dissect the model we will all learn something. Along the way it will give
me a chance to really understand Ryan's implementation of colimits.

Spending the rest of the day with my wife. One chore we have agreed on is
to pick up a new mouse. I really hate this touch pad.

**Comment by dspivak** [comment]
I agree that AQL feels more like a model-management tool than an ETL tool,
because we don't have great things to say about it's efficiency—that is, we
really don't know how well it performs.

Anyway, good luck with the colimit example, and happy holidays!

David

**Comment by wisnesky** [comment]
Re: scalability, there’s always the option of pushing computation to the data, rather than bringing data to the computation: for example, to implement an AQL program that imports/exports SQL data by emitting SQL/PSM and doing the computation in the RDBMS.  We know from FQL (more specifically, RelFound) exactly which portion of AQL is easy to implement this way; to handle the rest would be painful but not impossible.  Then the story repeats with other back ends like MapReduce, Informatica, etc.  There’s a real possibility we’ll be forced down this route, but it’s so much work that I don’t want to do it unless it’s definitely a user requirement.

**Comment by peterygates** [comment]
I don't think it is a question of whether it is a requirement but is it a
near term requirement. We should have in mind a vision (that is evolving
based on feedback from our imaginary customers) for where we are going with
the product. I think for now we have the right priorities.

I think pushing the computation to the data is definitely in our future at
some point.
