### ISSUE TITLE
Longer integer data creates errors

### ISSUE THREAD

**Issue by ssy248** [CategoricalData/fql#46]
When entering the phone number as an integer in the schema "Graphene Sample",

encountered error:
Error in instance GSInstance: In javascript execution of 5107192857 cannot convert to Integer, class java.lang.NumberFormatException error: For input string: "5107192857"

Possibly helpful info: javascript arguments are accessed as input[0], input[1], etc.

Possibly useful links: http://docs.oracle.com/javase/8/docs/api/ and http://docs.oracle.com/javase/8/docs/technotes/guides/scripting/nashorn/intro.html .

When shortening the numbers to only ~ 4 digits, the error was no longer there; for some reason it cannot convert the integer with more digits.

**Comment by wisnesky** [comment]
That's a good catch.  The reason this happens is that java uses 32-bit integers, which means the largest number that an Integer can represent is 2 billion.  So, you'll have to use String instead of Integer for phone numbers.

I have added a comment to the above effect to the error message that gets displayed.
