### ISSUE TITLE
can't build from source

### ISSUE THREAD

**Issue by freckletonj** [CategoricalData/fql#6]
`mvn package` doesn't terminate, but always ends up on an error (of sorts):

`Changes detected - recompiling the module!`

Then the terminal is stuck like that indefinitely, or until I `C-c` force quit it, and it uses up one of my processor cores completely throughout the process...

I'm on Ubuntu 14.04, and would love to give this project a try since, just last night, I fantasized about FQL (not knowing of it's existence yet) before realizing that *somebody* had probably made something, and a quick google search showed me all your awesome-looking work!

**Comment by wisnesky** [comment]
Hi Josh,

I don't know much about maven - anything maven related was contributed by a 3rd party - but I'll do my best to debug this error.

In the interim, you might try the compiled jar file available at categoricaldata.net/fql.html

⁣Ryan

**Comment by freckletonj** [comment]
Thanks, I'd tried that and got scared off by:

![image](https://cloud.githubusercontent.com/assets/8399149/19982048/13a30202-a1ca-11e6-94e5-2cb638553d6f.png)

I'll test it out though :)

**Comment by wisnesky** [comment]
Oh, that happens because I didn't cryptographically sign the deb file. Doing so is on my to-do list.  But I strongly suggest using the .jar file instead, because I update the jar file all the time but only build x86 binaries occasionally.

⁣

**Comment by freckletonj** [comment]
oh nice, I should've just done that!

jar works our of the box!

**Comment by wisnesky** [comment]
Great - let me know if you have any questions!

I took a look at the maven file, but it seems like all it does is specify the source root directory, say to use to eclipse compiler, and then note the specific version numbers of the included libraries.  So I don’t have a clue why it would be looping - which means that unfortunately this issue will have to go unresolved until a maven expert graciously steps in (which does happen from time to time.)

**Comment by DanielCoorey** [comment]
Hi Josh,

I'm no maven expert but I was the last to touch the project's pom.xml. I've been building the code with mvn but under an Eclipse Che workspace. Despite the whole point of having a build file, perhaps there's an environmental difference here that's causing the issue. If you need any help building as I've done, I'd be happy to help.

**Comment by wisnesky** [comment]
Both the Sun compiler and maven with the eclipse plugin appear to fail because of problems with type inference compared to the latest eclipse compiler. 

I changed the FQL source code to not be so hard on the java compiler and now FQL appears to compile fine with both the Sun compiler and the eclipse plugin, at least on my NetBeans installation.  I've committed the pom.xml file and will eventually close the issue if no more compilation errors are reported by FQL users.

--

More info:

Maven's incremental compilation has been known to loop forever do to staleness issues, e.g.,  http://stackoverflow.com/questions/17944108/maven-compiler-plugin-always-detecting-a-set-of-sources-as-stale.  Incremental compilation can be disabled using the 'useIncrementalCompilation' option - http://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html .  When I disabled it, compilation still failed with a null pointer exception, which resolved when I changed the FQL source to not be so hard on the java compiler.
