### ISSUE TITLE
MySQL JDBC compatibility

### ISSUE THREAD

**Issue by wisnesky** [CategoricalData/fql#8]
I believe I fixed the "concurrent result set" MySQL JDBC issue that we discovered today (Dec 15, 2016).  Can you please verify that MySQL JDBC import/export works correctly?  If verified, please close the issue; otherwise, please add a comment and assign the bug to me.

**Comment by peterygates** [comment]
I attempted to downloaded the latest build. I right clicked on the link in "As a Java Jar..." and selected save as link and saved it on my desktop with the same as the existing version of fql.jar. I then opened fql using the fqlmysql.bat file and got the same error as yesterday. I tried to verify that I had successfully downloaded the most recent version by checking the help about menu item, but no version information indicated. I assume I did test the latest build by it might be helpful to be able to verify which version I am running so that I am sure. For now I am leaving this an open issue.

**Comment by wisnesky** [comment]
It turns out this bug has nothing to do with MySQL.  What is happening is that the employee and department tables contain overlapping IDs.  In an AQL instance, every generator must be unique; so AQL was trying to construct an instance with generators like 

0:Employee 
0:Department

The requirement that AQL IDs be unique was arrived at after considerable thought (it has some compelling advantages) and can't be changed now, so the fix is to distinguish the IDs during import.  Try something like the following:

instance J = import_jdbc ... {
    Employee -> "SELECT concat(\"emp\",id) FROM Employee"
    Department -> "SELECT concat(\"dept\",id) FROM Dept"
    worksIn -> "SELECT concat(\"emp\",id), concat(\"dept\",worksIn) FROM Employee" 
}

I imagine this issue will recur, so I will add a remark to the error message describing the work around.  Please try the work around and close the issue if it is fixed.

**Comment by peterygates** [comment]
I should have seen that comming. My bad. My practice is independent
interger sequences for surrogate keys. This means collisions should be
expected. It actually crossed my mind this could be a problem, but failed
to make the connection from the error message.

You let your distaste for mysql lead you down the wrong path. live and
learn.

**Comment by peterygates** [comment]
I fear this will be so common that we should automatically prefix integer
ids with some disambiguation string like tablename_intid. Let me think
about this. got to go on airplane mode.

**Comment by wisnesky** [comment]
I wouldn't add auto disambiguation by default, but we could add it as an option during JDBC/CSV import.  I'll open an issue.

There might be a dual issue to remove prefixes during export, but it isn't clear to me what this would look like.

Anyway, do please try MySQL again and close this issue if you can get MySQL import to work using the work around.

**Comment by peterygates** [comment]
I will close this issue. Having given it some thought I don't want to make this automatic. the fix is easy and should be in the hands of the person doing the import. I think a better error message is the only thing you need to do.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Ryan Wisnesky <notifications@github.com> Date: 12/16/16  3:39 PM  (GMT-05:00) To: CategoricalData/fql <fql@noreply.github.com> Cc: peterygates <peter@catinf.com>, Assign <assign@noreply.github.com> Subject: Re: [CategoricalData/fql] MySQL JDBC compatibility (#8) 
I wouldn't add auto disambiguation by default, but we could add it as an option during JDBC/CSV import.  I'll open an issue.
There might be a dual issue to remove prefixes during export, but it isn't clear to me what this would look like.
Anyway, do please try MySQL again and close this issue if you can get MySQL import to work using the work around.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CategoricalData/fql","title":"CategoricalData/fql","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CategoricalData/fql"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wisnesky in #8: I wouldn't add auto disambiguation by default, but we could add it as an option during JDBC/CSV import.  I'll open an issue.\r\n\r\nThere might be a dual issue to remove prefixes during export, but it isn't clear to me what this would look like.\r\n\r\nAnyway, do please try MySQL again and close this issue if you can get MySQL import to work using the work around."}],"action":{"name":"View Issue","url":"https://github.com/CategoricalData/fql/issues/8#issuecomment-267690708"}}}

**Comment by peterygates** [comment]
This works:

instance J = import_jdbc 
"com.mysql.jdbc.Driver"
"jdbc:mysql://localhost:3306/employees?user=root&password=HappyFunctor" 
 : S2 {
	Employee -> "SELECT concat('e', id) FROM Employee"
	Department -> "SELECT concat('d', id) FROM Department"
  	department -> "SELECT concat('e', id), concat('d', department_id) FROM Employee"
	first -> "SELECT concat('e', id), first_name FROM Employee"
  	last	-> "SELECT concat('e', id), last_name FROM Employee"
  	name -> "SELECT concat('d', id), name FROM Department"
}
