### ISSUE TITLE
Allow inverse functions in Typeside

### ISSUE THREAD

**Issue by phreed** [CategoricalData/fql#96]
The theory uses mathematical functions i.e. they are mappings.
When generating sigma and pi functors the inverse is necessary.
The typesides do not presently support inverse functions.

**Comment by wisnesky** [comment]
I'm not entirely sure what this is asking for.  Let F : S -> T be a schema mapping, where S and T are on typeside Ty.  It is a theorem that Sigma_F, Pi_F, and Delta_F always exist, even if the functions in Ty do not have inverses (although, as usual, Sigma/Pi could emit an infinite instance).  There are limitations to what AQL can do when Ty is "java based", but these limitations do not exist if Ty does not use java.  Hopefully the attached file can clarify what happens:

typeside Ty = literal {
	types
		String
		Integer
	constants
		50 : Integer	
	functions
		str_to_int : String -> Integer
		int_to_str : Integer -> String
}

schema S = literal : Ty {
	entities
		S_E
	attributes
		S_att : S_E -> String	
}

schema T = literal : Ty {
	entities
		T_E
	attributes
		T_att : T_E -> Integer	
}

mapping F = literal : S -> T {
	entities
		S_E -> T_E
	attributes
		S_att -> T_att . int_to_str	
}

instance I = literal : T  {
	generators
		g : T_E
	equations
		g.T_att = 50	
}

instance J = delta F I // works fine

instance K = sigma F J { // works fine
	options
		require_consistency = false
}
/*
The instance K is

generators
	g : T_E

equations
	g.T_att.int_to_str = 50
 */

**Comment by phreed** [comment]
Maybe I misunderstood.
I thought there was a problem in ...
```
instance K = sigma F J
```
...because it did not know to use `str_to_int`.
And, that `require_consistency = false` was (in some sense) losing information.

**Comment by wisnesky** [comment]
I edited the example to remove str_to_int, to make it to clear that sigma_F is not inverting delta_F - in general, the relationship between the two is one of adjunction, not inverse.

The require_consistency = false is required because the type algebra - an equational theory associated with each instance - is not free for K.  There's nothing wrong with this, it is just unusual so the tool requires the flag to be set.

**Comment by wisnesky** [comment]
To elaborate, the instance K, as an equational theory, possibly (not necessarily) proves more equations between ints than the typeside does (K is not conservative over the typeside).  AQL requires you to acknowledge this by setting require_consistency = false, because if you're not careful you can run into things like instances for which 1 = 2.  But everything is fine here; I think you may be noticing that AQL is a "deductive" database, not an "extensional" or "computational" one.

**Comment by wisnesky** [comment]
BTW, if you add function str_to_int and equation int_to_str . str_to_int = id to the type side, then the instance K proves that g.T_att = 50.  Without that equation, K does not prove that g.T_att = 50.

**Comment by phreed** [comment]
Ah, that is what I was not seeing.
```
typeside Ty = literal {
  types
     String
     Integer
  constants
      50 : Integer
  functions
      int_to_str : Integer -> String
      str_to_int : String -> Integer
  equations
      int_to_str . str_to_int = id
}
```
I will make a sample file for Typeside Tricks.
